name: Hit Supabase Youtube Video Endpoint Every 6 Days

on:
  schedule:
    - cron: "0 0 */5 * *"

jobs:
  hit-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Hit endpoint
        run: curl -X GET https://vasqhjczkzaqsexezhhn.functions.supabase.co/youtube-videos
